
name: 'Build angular webapp'
description: 'Build angular webapp'
inputs:
  EnvironmentConfig:
    description: 'Environment to build'
    required: true
  AngularVersion:
    description: 'Angular version'
    required: true
  NodeVersion:
    description: 'Node version'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      name: 'Provisioning Node ${{ inputs.NodeVersion }}'
      with:
        node-version: ${{ inputs.NodeVersion }}
    - name: 'Prepare binaries'
      shell: bash
      run: |
        pwd
        ls -ltra
        npm install -g @angular/cli@${{ inputs.AngularVersion }}
        npm install
        ng build --configuration=${{ inputs.EnvironmentConfig }}